name: Release

on:
  workflow_dispatch:

jobs:
  approve_and_release:
    runs-on: ubuntu-latest
    environment: production  # This specifies the environment that requires approval

    steps:
      - name: Print Approval Message
        run: echo "Hello, World! This is the release process."

      - name: Notify Release
        run: echo "Notifying the stakeholders about the released "
