name: Generate Resume

on:
  push:
    branches:
      - main  # Adjust if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version

      - name: Install dependencies
        run: |
          pip install python-docx

      - name: Run script to generate resume
        run: python resume.py  # This is your script name

      - name: Upload resume
        uses: actions/upload-artifact@v2
        with:
          name: Kishore_Resume
          path: Kishore_Resume_Final_Reordered.docx  # Ensure this matches the output filename in your script
